sudo: required
language: java
jdk: openjdk11
services:
- docker
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
- pip3 install awscli --upgrade --user
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --no-include-email --region us-west-2)
script:
  mvn verify
env:
  global:
  - secure: "Dq47Qt9BB7FIIcTtc79MajKvoCg/KmwHBLD08/lcAhBmPPRrl3qHV+65euuRg5EdDeFTo0tAJcpCrgW6ieqbXYMe2XrIVPhzXGWgaOzY2xDfCar3YzReSQYTJcKLlj/v+dYjKQlRr7RxWDlKnk+fs/A+5JRuL9/8IcJXDf5npMR+xXdIycaCyPoMXbD7yAXWBSn3rSz2hvpIvHP1FnVeSWXxmqPIgxA4RsKzKn1LDfC1BOEHVPT3Ie65jpQVmUUCc3sxHLq5gsYP0ItTMAUsxKgMiSvWqGdKVMa1AnYV9wDkk26rZovGw41jrAn4VDozFQShbmO523jmg5IABe+SRicHr0ezv/9SwJNeDJ+M8gAJ9RRqyM4bZX6rXYALQMLjt33efq1k+uuc/Gzu+8Pl2QOFx7ceBNuhgUK2/pE6qBijRY/+YGeK+//CNeg+oQ3LmzuJj38flq4aTbvoqqSIsosXKUL3zuKz689ZQJ5nJiwiFb545mq5XK7UlWrG3IJRvsj0ZVNvd/oBMq2NQmHwlXoUxCqZ9oDR+lNXGjFVN/8LU508vERGxU8PS871tXnPGKArTc2WZGTnjGDmm6o6OPxMtLvXJZezEK1AgHlkBKd6RLaIvgbpuBmHgUvQZRWml2FzaqR+oAVWMWHjhAOxgPCyb07hcuZusENp8Q/VTgo="
  - secure: "GzUMiYTiD1ZUj4mP4cihcTbT6mp8hPHrHU+QylEuQjuZYfpxe0AL3GJDz5UBl8F07Z3EwC5GBXbrP050ECVcwCVTcjRj7qlT0K0tl+r2t2E9GXSqOlnN+KS5zDHO/uH8QXQ2CLA7OWpkVhmQA08iaa1fhhYhNXUKvKiMrYLrwCUEn7K+2JgW97IXEKpfhYZbsmtaOC6+0qeKL7FDrvW+oHJ9k2zP0tHlJNlr42DUp4bJ4XmvrJMhbwAtNDQQm6vNSbPSNIRmrf1LvbHS7Oa7shG9ztNfWjCg1IECo2FzMjGJsB1t25NNGissWv5x8YmHJPk/OHBxJwDiRQnhlWwx6S0e1DV0EYADfgvFPx4/2Zyy46ivvv6NByIDfT1wyrrCQfpI++3pfgMCdxXwvOUdAw0O9s+INw3pnOs5WMyq3c+1xcHud7YsaIGUTyQ3JSPbU1VYm22pq2zReA86w1VQ8YaTwHcaLIRNFqgUdmNy+g/cEmHGALtSyD/eAMwnRXOnoTKzjRAix2O2KsbUxjxBdAZ2ccllzoa7xKVId7V602Gr7PbhbaRemhYgJ1p3E2eYlKNreZiRUP8n3RmSJStorAgLvi5fOjtOC46GgTdGOzVqU8tUik9CNsmk0A9EMvh2fHlr1CLfMw2g+ouDm9YpqncMOkzN095mfDPQ+S5g3pY="
  - secure: "l5BriYMkY5bKjG3KNWPPRB8RmvZw78m2CMwPUDJgM2QRAM+QuUtrN8FFH8SZSMoRqbHuo8Kl+wCyBLkQk3+n9deA4cDoX/inHP2JdrZERs99o6L7rBE2HCvx+CIpas1Kms+aqQyWv/JUYLraawurcKN2aEliKfp14uwFlAt7tSe8qM6LG0UJJckzY2+K38629z0ejvlt+wCQju/KAqk+KKwuY14dYloLbPcNWeFom/MWmRtzsYD/e1w67mMK312QGnM2t3pX1YjWqrXc5nuTJ4JnZjKfXrGIu9BEuQTAoCuwV+WNEXch9Z6HrpQfzZmI5HCrOzGtbmYRzXmqekOu/sxYPiXt8GRH2VQJVThegRODrtGPt4r94skrCP7TJQklo4ZvHqv0t5u7/dh6vDr+rmpwyX6fZA1mcdIBiqa5XxgtuviuibOPMs6DFrvRQP6c2K/wUJZoZjvibo6O32yENF42ZjwfD7ZgHHmYWq9wsUb4XKqFTV+2Izw6q4QvALzk9Z9CDY+1WAlXPOP8/wGG23cgUj0uutfE4Nnhh/FtGb5ujZVwfiu6XP9jzrcWHLCht5LnU4othnyq2PO1bT4DjdnmM+RtyhTNIA2gGmLfhA5agv0y0d737TcKot66mj2UVm/MfDqB50kKUGe3qlmNrnhXFXVxUxD4H4GbRgMUYzs="